name: Correction
description: Suggest a correction to the list!
title: "[Correction]"
labels: ["Correction"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Issue will be closed if incomplete. These are required before submitting and by submitting you agree that you have actually done them.
      options:
        - label: I've checked that this correction is valid and accurate.
          required: true
        - label: I've checked that this correction has not already been suggested.
          required: true
  - type: input
    attributes:
      label: What plugin is this correction for?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What section(s) of the list is this correction for?
      description: Select all that apply. Where the plugin is located in the lists
      multiple: true
      options:
        - Performance
        - Bugfixes
        - Enhancements
        - Software
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What version(s) dose this correction apply to?
      multiple: true
      options:
        - 1.8.X or earlier
        - 1.12.X
        - 1.14.X
        - 1.16.X
        - 1.17.X
        - 1.18.X
        - 1.19.X
        - All versions
        - Not applicable
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What platform(s) dose this correction apply to?
      multiple: true
      options:
        - Spigot
        - Paper
        - Purpur
        - Bungeecord
        - Velocity
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: What needs correcting?
      description: Please provide a detailed description of the correction. If you are correcting a link, please provide the correct link.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input relevant link(s) which can be used to verify the correction.
      description: Please provide a link to the source of the correction. Pictures are also accepted if they are relevant.
    validations:
      required: true
  - type: textarea
    attributes:
      label: (OPTIONAL) Any extra information about the correction.
